### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by DanielBoigk** [CubensisAI/flutter_templates#1]
- [ ] add Flutter-Rust Bridge
- [ ] Get Markdown widget to run.
- [ ] Try Html in Markdown widget.
- [ ] write small routine that fetches MathJax or typst code from string.
- [ ] Try Latex widget
- [ ] Ask the typst guys about how to integrate typst.
- [ ] Write structs for n-categories and their objects and morphisms.
- [ ] Fill with some examples
- [ ] Render those examples
- [ ] Show to others

**Comment by DanielBoigk** [comment]
Other tasks:
- Setup Github actions
- Get the web version running somewhere
